name: Stock Genius US

on:
  schedule:
    # 夏令時間（05:00 UTC+8）
    - cron: "0 21 * * 1-5"

    # 冬令時間（06:00 UTC+8）
    - cron: "0 22 * * 1-5"

  workflow_dispatch:

jobs:
  genius_us:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r repos/Stock-Genius-System/requirements.txt

      - name: Run Stock Genius US
        env:
          DISCORD_WEBHOOK_US: ${{ secrets.DISCORD_WEBHOOK_US }}
        run: |
          python repos/Stock-Genius-System/scripts/ai_us_post.py
