name: vault-clean
on:
  schedule:
    - cron: "0 3 * * *"   # 時間你不用再管
  workflow_dispatch:

jobs:
  clean:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run Vault Cleanup
        shell: powershell
        run: |
          python vault/run_vault_cleanup.py
